### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by iGetUploaded** [moom825/batch-obfuscator-made-in-python#4]
So I obfuscated my bat file but not it doesn't seem to run like I try to open it and then it automatically closes it even when I try to run it as Admin. Not sure what's wrong any ideas

**Comment by moom825** [comment]
can you send the batch file your using?

**Comment by iGetUploaded** [comment]
Hi, Sorry for late response but It wont let me send it here

**Comment by moom825** [comment]
you can try sending it to me over discord, my discord is moom825#0001
