### ISSUE TITLE
bad and lame, easy to deobf..

### ISSUE THREAD

**Issue by EvilBytecode** [moom825/batch-obfuscator-made-in-python#7]
https://github.com/EvilBytecode/Batch-Deobfuscator

make it better, echo trap exists..

**Comment by moom825** [comment]
lmao

**Comment by EvilBytecode** [comment]
had to be honest, same goes for kdot's obfuscator

**Comment by moom825** [comment]
tbh, i made this shit 3 years ago. you can shit on it all u want lol

**Comment by EvilBytecode** [comment]
all good, all obfuscators are bad on github lmfao can deobf any sh here 🤣 , but  besides this repo you have cool ones 👍 so dont take it personally
